# Copyright 2025 Alejandro Martínez Corriá and the Thinkube contributors
# SPDX-License-Identifier: Apache-2.0

---
galaxy_info:
  author: Alejandro Martínez Corriá
  description: Common role for GitHub SSH key management
  license: Apache-2.0
  min_ansible_version: 2.9
  platforms:
    - name: GenericLinux
      versions:
        - all
  galaxy_tags:
    - github
    - ssh
    - deployment
    - devops

dependencies: []