# Copyright 2025 Alejandro Martínez Corriá and the Thinkube contributors
# SPDX-License-Identifier: Apache-2.0

---
# ansible/40_thinkube/core/juicefs/17_configure_discovery.yaml
# Description:
#   Configure service discovery for JuiceFS by creating a ConfigMap
#   that describes the service endpoints and metadata
#
# Requirements:
#   - JuiceFS must be deployed
#   - MicroK8s kubectl access
#
# Usage:
#   cd ~/thinkube
#   ./scripts/run_ansible.sh ansible/40_thinkube/core/juicefs/17_configure_discovery.yaml
#
# Variables from inventory:
#   - kubeconfig: Path to kubeconfig file

- name: Configure JuiceFS service discovery
  hosts: microk8s_control_plane
  gather_facts: true

  tasks:
    - name: Create service discovery ConfigMap
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        state: present
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: thinkube-service-config
            namespace: kube-system
            labels:
              thinkube.io/managed: "true"
              thinkube.io/service-type: "core"
              thinkube.io/service-name: "juicefs"
          data:
            service.yaml: |
              service:
                name: juicefs
                display_name: "JuiceFS"
                description: "Distributed RWX filesystem for multi-node storage"
                type: core
                category: storage
                icon: /icons/tk_data.svg

                endpoints:
                  - name: "Dashboard"
                    url: "https://juicefs.{{ domain_name }}"
                    type: "http"
                    primary: true
                    internal: false

                dependencies:
                  - postgresql
                  - seaweedfs

                scaling:
                  resource_type: statefulset
                  resource_name: juicefs-csi-controller
                  namespace: kube-system
                  min_replicas: 1
                  can_disable: false

                environment_variables:
                  - name: KUBECONFIG
                    value: "/home/jovyan/.kube/config"

    - name: Verify ConfigMap creation
      kubernetes.core.k8s_info:
        kubeconfig: "{{ kubeconfig }}"
        api_version: v1
        kind: ConfigMap
        name: thinkube-service-config
        namespace: kube-system
      register: configmap_info

    - name: Display ConfigMap status
      ansible.builtin.debug:
        msg: "Service discovery ConfigMap created for JuiceFS with dashboard endpoint"
      when: configmap_info.resources | length > 0
