# Copyright 2025 Alejandro Martínez Corriá and the Thinkube contributors
# SPDX-License-Identifier: Apache-2.0

---
# ansible/40_thinkube/optional/superset/17_configure_discovery.yaml
# Description:
#   Configure service discovery for Apache Superset by creating a ConfigMap
#   that describes the service endpoints and metadata
#
# Requirements:
#   - Superset must be deployed
#   - MicroK8s kubectl access
#
# Usage:
#   cd ~/thinkube
#   ./scripts/run_ansible.sh ansible/40_thinkube/optional/superset/17_configure_discovery.yaml
#
# Variables from inventory:
#   - domain_name: Base domain for the cluster
#   - kubeconfig: Path to kubeconfig file
#
# 🤖 AI-assisted

- name: Configure Superset service discovery
  hosts: microk8s_control_plane
  gather_facts: true

  vars:
    superset_hostname: "superset.{{ domain_name }}"
    superset_namespace: "superset"
    superset_client_id: "superset"

  tasks:
    - name: Get Superset client secret from Keycloak
      kubernetes.core.k8s_info:
        kubeconfig: "{{ kubeconfig }}"
        api_version: v1
        kind: Secret
        namespace: "{{ superset_namespace }}"
        name: superset-config
      register: superset_secret
      failed_when: superset_secret.resources | length == 0

    - name: Create service discovery ConfigMap
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        state: present
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: superset-service-info
            namespace: "{{ superset_namespace }}"
            labels:
              app.kubernetes.io/name: superset
              app.kubernetes.io/component: service-discovery
          data:
            service-name: "Apache Superset"
            service-type: "data-visualization"
            service-description: "Modern data exploration and visualization platform"
            service-url: "https://{{ superset_hostname }}"
            service-namespace: "{{ superset_namespace }}"
            service-port: "8088"
            auth-type: "keycloak-oidc"
            auth-realm: "{{ keycloak_realm }}"
            auth-client-id: "{{ superset_client_id }}"
            capabilities: "dashboards,sql-lab,charts,data-sources"
            data-sources: "prometheus,postgresql,opensearch,clickhouse"
            license: "Apache-2.0"

    - name: Service discovery configured
      ansible.builtin.debug:
        msg:
          - "Service discovery ConfigMap created for Superset"
          - "ConfigMap: superset-service-info in namespace {{ superset_namespace }}"
