# Copyright 2025 Alejandro Martínez Corriá and the Thinkube contributors
# SPDX-License-Identifier: Apache-2.0

# Thinkube custom values for Apache Superset Helm chart
# Based on: https://github.com/apache/superset/blob/master/helm/superset/values.yaml
# This file is processed as an Ansible template

# Use -dev image which includes psycopg2-binary and redis
image:
  repository: apache/superset
  tag: latest-dev
  pullPolicy: IfNotPresent

# Disable built-in PostgreSQL - use existing Thinkube PostgreSQL
postgresql:
  enabled: false

# Disable built-in Redis - use existing Thinkube Valkey
redis:
  enabled: false

# Superset node configuration
supersetNode:
  replicas:
    enabled: true
    replicaCount: 1

  connections:
    # External PostgreSQL configuration
    db_type: "postgresql"
    db_host: "{{ postgres_service }}"
    db_port: "{{ postgres_port }}"
    db_user: "{{ superset_db_user }}"
    db_pass: "{{ superset_db_password }}"
    db_name: "{{ superset_db_name }}"

    # External Valkey (Redis) configuration
    redis_host: "{{ valkey_service }}"
    redis_port: "{{ valkey_port }}"
    redis_user: ""
    redis_cache_db: "1"
    redis_celery_db: "0"
    redis_ssl:
      enabled: false

# Ingress configuration
ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
  hosts:
    - "{{ superset_hostname }}"
  path: /
  pathType: Prefix
  tls:
    - secretName: "{{ superset_tls_secret_name }}"
      hosts:
        - "{{ superset_hostname }}"

# Resource limits
resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 250m
    memory: 512Mi

# Init admin user
init:
  adminUser:
    username: "{{ admin_username }}"
    firstname: Admin
    lastname: User
    email: "admin@{{ domain_name }}"
    password: "{{ admin_password }}"

# Secret key for Flask
extraSecretEnv:
  SUPERSET_SECRET_KEY: "{{ superset_secret_key }}"
