# Copyright 2025 Alejandro Martínez Corriá and the Thinkube contributors
# SPDX-License-Identifier: Apache-2.0

---
# ansible/40_thinkube/core/dns-server/19_rollback.yaml
# Description:
#   Rollback BIND9 DNS server deployment
#
# Usage:
#   cd ~/thinkube
#   ./scripts/run_ansible.sh ansible/40_thinkube/core/dns-server/19_rollback.yaml
#
# 🤖 [AI-assisted]

- name: Rollback BIND9 DNS Server
  hosts: k8s_control_plane
  gather_facts: false
  become: true
  
  vars:
    dns_namespace: "dns-system"
    kubeconfig: /var/snap/microk8s/current/credentials/client.config
    kubectl_bin: microk8s kubectl
    
  tasks:
    - name: Delete BIND9 deployment
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        state: absent
        api_version: apps/v1
        kind: Deployment
        name: bind9
        namespace: "{{ dns_namespace }}"
        
    - name: Delete BIND9 services
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        state: absent
        api_version: v1
        kind: Service
        name: "{{ item }}"
        namespace: "{{ dns_namespace }}"
      loop:
        - bind9-external
        - bind9-internal
        
    - name: Delete BIND9 ConfigMaps
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        state: absent
        api_version: v1
        kind: ConfigMap
        name: "{{ item }}"
        namespace: "{{ dns_namespace }}"
      loop:
        - bind9-config
        - bind9-zones
        
    - name: Delete DNS namespace
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        state: absent
        api_version: v1
        kind: Namespace
        name: "{{ dns_namespace }}"
        
    - name: Display rollback complete message
      ansible.builtin.debug:
        msg: |
          BIND9 DNS server has been removed.
          
          Note: You may need to update node DNS configurations
          to use an alternative DNS server.