# Copyright 2025 Alejandro Martínez Corriá and the Thinkube contributors
# SPDX-License-Identifier: Apache-2.0

---
# ansible/40_thinkube/optional/nats/19_rollback.yaml
# Description:
#   Rollback NATS deployment and clean up all resources
#
# Requirements:
#   - MicroK8s must be installed
#   - kubectl access configured
#
# Usage:
#   cd ~/thinkube
#   ./scripts/run_ansible.sh ansible/40_thinkube/optional/nats/19_rollback.yaml
#
# Variables from inventory:
#   - kubeconfig: Path to kubectl configuration
#   - kubectl_bin: Path to kubectl binary
#   - helm_bin: Path to helm binary
#   - nats_namespace: Namespace for NATS
#
# 🤖 [AI-assisted]

- name: Rollback NATS deployment
  hosts: k8s_control_plane
  gather_facts: true

  vars:
    k8s_namespace: "nats"

  tasks:
    - name: Uninstall NATS Helm release
      kubernetes.core.helm:
        binary_path: "{{ helm_bin }}"
        kubeconfig: "{{ kubeconfig }}"
        name: "nats"
        release_namespace: "{{ k8s_namespace }}"
        state: absent
      failed_when: false

    - name: Delete NATS namespace (and all resources within)
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        state: absent
        kind: Namespace
        name: "{{ k8s_namespace }}"
      failed_when: false

    - name: Remove NATS Helm repository
      kubernetes.core.helm_repository:
        binary_path: "{{ helm_bin }}"
        name: nats
        state: absent
      failed_when: false

    - name: Display rollback completion
      ansible.builtin.debug:
        msg:
          - "NATS rollback completed"
          - "-----------------------------------"
          - "Removed Helm release: nats"
          - "Removed namespace: {{ k8s_namespace }}"
          - "Removed Helm repository: nats"
          - "-----------------------------------"