# Copyright 2025 Alejandro Martínez Corriá and the Thinkube contributors
# SPDX-License-Identifier: Apache-2.0

# roles/valkey/ephemeral_valkey/meta/main.yaml
---
galaxy_info:
  author: Alejandro Martínez Corriá
  description: Deploy ephemeral Valkey (Redis-compatible key-value store) for session storage
  license: Apache-2.0
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - valkey
    - redis
    - cache
    - session
    - kubernetes
    - k8s

dependencies: []