# Copyright 2025 Alejandro Martínez Corriá and the Thinkube contributors
# SPDX-License-Identifier: Apache-2.0

---
# ansible/40_thinkube/optional/chroma/00_install.yaml
# Description:
#   Orchestrator playbook for Chroma vector database installation
#   This playbook calls the individual playbooks in the correct order
#
# Requirements:
#   - MicroK8s must be installed and running
#   - ADMIN_PASSWORD environment variable must be set
#
# Usage:
#   cd ~/thinkube
#   ./scripts/run_ansible.sh ansible/40_thinkube/optional/chroma/00_install.yaml
#
# 🤖 AI-assisted

- name: Chroma - Deploy
  import_playbook: 10_deploy.yaml

- name: Chroma - Configure Service Discovery
  import_playbook: 17_configure_discovery.yaml