# Copyright 2025 Alejandro Martínez Corriá and the Thinkube contributors
# SPDX-License-Identifier: Apache-2.0

---
# Adapted from ansible/misc/tasks/00_core_shell_setup.yml
# Core Shell Setup - Create directory structure in code-server pod
# Note: Packages (git, curl, zsh, fish, jq) are pre-installed in Dockerfile

- name: Create Thinkube shared shell directories in pod
  ansible.builtin.shell: |
    {{ kubectl_bin }} exec -n {{ code_server_namespace }} {{ codeserver_pod }} -- \
      sh -c "mkdir -p {{ item }} && chown 1000:1000 {{ item }}"
  loop:
    - "{{ thinkube_system_dir }}"
    - "{{ thinkube_system_functions_dir }}"
    - "{{ thinkube_system_docs_dir }}"
    - "{{ thinkube_system_aliases_dir }}"
    - "{{ thinkube_user_dir }}"
    - "{{ thinkube_user_functions_dir }}"
    - "{{ thinkube_user_aliases_dir }}"
  changed_when: true
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  tags: [thinkube, setup]
