# Copyright 2025 Alejandro Martínez Corriá and the Thinkube contributors
# SPDX-License-Identifier: Apache-2.0

---
# Adapted from ansible/misc/tasks/00_core_shell_setup.yml
# Core Shell Setup - Create directory structure in code-server pod
# Note: Packages (git, curl, zsh, fish, jq) are pre-installed in Dockerfile

- name: Create Thinkube shared shell directories in pod
  ansible.builtin.command:
    cmd: >
      k8s kubectl exec -n {{ code_server_namespace }} {{ codeserver_pod }} --
      mkdir -p {{ item }}
  loop:
    - "{{ thinkube_system_dir }}"
    - "{{ thinkube_system_functions_dir }}"
    - "{{ thinkube_system_docs_dir }}"
    - "{{ thinkube_system_aliases_dir }}"
    - "{{ thinkube_user_dir }}"
    - "{{ thinkube_user_functions_dir }}"
    - "{{ thinkube_user_aliases_dir }}"
  changed_when: true
  tags: [thinkube, setup]
