# Copyright 2025 Alejandro Martínez Corriá and the Thinkube contributors
# SPDX-License-Identifier: Apache-2.0

---
# Adapted from ansible/misc/tasks/01_starship_setup.yml
# Starship Setup - Configure Starship prompt (pre-installed in Dockerfile)

- name: Create config directory for Starship
  ansible.builtin.command:
    cmd: >
      k8s kubectl exec -n {{ code_server_namespace }} {{ codeserver_pod }} --
      mkdir -p {{ starship_config_dir }}
  changed_when: false
  tags: [starship]

- name: Create temp directory for starship config
  ansible.builtin.tempfile:
    state: directory
    suffix: starship
  register: temp_starship_dir
  tags: [starship]

- name: Copy starship.toml to temp directory on host
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/files/starship.toml"
    dest: "{{ temp_starship_dir.path }}/starship.toml"
    mode: '0644'
  tags: [starship]

- name: Copy Starship configuration to pod
  ansible.builtin.command:
    cmd: >
      k8s kubectl cp
      {{ temp_starship_dir.path }}/starship.toml
      {{ code_server_namespace }}/{{ codeserver_pod }}:{{ starship_config_dir }}/starship.toml
  changed_when: true
  tags: [starship]

- name: Clean up temp directory
  ansible.builtin.file:
    path: "{{ temp_starship_dir.path }}"
    state: absent
  tags: [starship]

- name: Set starship available fact
  ansible.builtin.set_fact:
    starship_available: true
  tags: [starship]
