# Copyright 2025 Alejandro Martínez Corriá and the Thinkube contributors
# SPDX-License-Identifier: Apache-2.0

---
# ansible/40_thinkube/optional/monitoring/00_install.yaml
# Description:
#   Orchestrator playbook that runs all Monitoring stack playbooks in sequence
#   This installs Prometheus and Grafana with full integration
#
# Requirements:
#   - MicroK8s must be installed and running
#   - Keycloak must be deployed (for Grafana SSO)
#   - Ingress controller must be deployed
#
# Usage:
#   cd ~/thinkube
#   ./scripts/run_ansible.sh ansible/40_thinkube/optional/monitoring/00_install.yaml
#
# Variables from inventory:
#   - All variables required by individual playbooks
#

- name: Monitoring - Deploy Prometheus
  import_playbook: 10_deploy_prometheus.yaml
  
- name: Monitoring - Configure Prometheus Scraping
  import_playbook: 11_configure_prometheus_scraping.yaml
  
- name: Monitoring - Configure Grafana Keycloak Integration
  import_playbook: 12_configure_grafana_keycloak.yaml
  
- name: Monitoring - Deploy Grafana
  import_playbook: 13_deploy_grafana.yaml
  
- name: Monitoring - Import Grafana Dashboards
  import_playbook: 14_import_grafana_dashboards.yaml
  
- name: Monitoring - Configure Service Discovery
  import_playbook: 17_configure_discovery.yaml