# Copyright 2025 Alejandro Martínez Corriá and the Thinkube contributors
# SPDX-License-Identifier: Apache-2.0

---
# ansible/40_thinkube/optional/monitoring/17_configure_discovery.yaml
# Description:
#   Configure service discovery for Prometheus and Grafana by creating ConfigMaps
#   that describe the service endpoints and metadata
#
# Requirements:
#   - Prometheus and Grafana must be deployed
#   - MicroK8s kubectl access
#
# Usage:
#   cd ~/thinkube
#   ./scripts/run_ansible.sh ansible/40_thinkube/optional/monitoring/17_configure_discovery.yaml
#
# Variables from inventory:
#   - domain_name: Base domain for the cluster
#   - kubeconfig: Path to kubeconfig file

- name: Configure monitoring services discovery
  hosts: microk8s_control_plane
  gather_facts: true
  
  tasks:
    - name: Create monitoring service discovery ConfigMap (for Optional Components)
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        state: present
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: thinkube-service-config
            namespace: monitoring
            labels:
              thinkube.io/managed: "true"
              thinkube.io/service-type: "optional"
              thinkube.io/component: "monitoring-stack"
          data:
            # This is used by Optional Components to detect installation
            installed: "true"
            installed_at: "{{ ansible_date_time.iso8601 }}"
            components: "prometheus,grafana"
    
    - name: Create Prometheus service discovery ConfigMap
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        state: present
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: thinkube-service-config-prometheus
            namespace: monitoring
            labels:
              thinkube.io/managed: "true"
              thinkube.io/service-type: "optional"
              thinkube.io/service-name: "prometheus"
          data:
            service.yaml: |
              service:
                name: prometheus
                display_name: "Prometheus"
                description: "Metrics collection and monitoring"
                type: optional
                category: monitoring
                icon: /icons/tk_observability.svg
                
                endpoints:
                  - name: web
                    type: http
                    url: "https://prometheus.{{ domain_name }}"
                    health_path: "/-/healthy"
                    description: "Web UI and query interface"
                    primary: true
                    
                  - name: metrics
                    type: http
                    url: "https://prometheus.{{ domain_name }}"
                    health_path: "/metrics"
                    description: "Prometheus metrics endpoint"
                    
                dependencies: []
                  
                scaling:
                  resource_type: statefulset
                  resource_name: prometheus
                  namespace: monitoring
                  min_replicas: 1
                  can_disable: true
                  
    - name: Create Grafana service discovery ConfigMap
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        state: present
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: thinkube-service-config-grafana
            namespace: monitoring
            labels:
              thinkube.io/managed: "true"
              thinkube.io/service-type: "optional"
              thinkube.io/service-name: "grafana"
          data:
            service.yaml: |
              service:
                name: grafana
                display_name: "Grafana"
                description: "Metrics visualization and dashboards"
                type: optional
                category: monitoring
                icon: /icons/tk_observability.svg
                
                endpoints:
                  - name: web
                    type: http
                    url: "https://grafana.{{ domain_name }}"
                    health_path: "/api/health"
                    description: "Dashboard UI"
                    primary: true
                    
                  - name: api
                    type: http
                    url: "https://grafana.{{ domain_name }}"
                    health_path: "/api/org"
                    description: "Grafana API"
                    
                dependencies:
                  - prometheus
                  
                scaling:
                  resource_type: deployment
                  resource_name: grafana
                  namespace: monitoring
                  min_replicas: 1
                  can_disable: true
                  
    - name: Verify monitoring ConfigMap creation
      kubernetes.core.k8s_info:
        kubeconfig: "{{ kubeconfig }}"
        api_version: v1
        kind: ConfigMap
        name: thinkube-service-config
        namespace: monitoring
      register: monitoring_configmap
      
    - name: Verify Prometheus ConfigMap creation
      kubernetes.core.k8s_info:
        kubeconfig: "{{ kubeconfig }}"
        api_version: v1
        kind: ConfigMap
        name: thinkube-service-config-prometheus
        namespace: monitoring
      register: prometheus_configmap
      
    - name: Verify Grafana ConfigMap creation
      kubernetes.core.k8s_info:
        kubeconfig: "{{ kubeconfig }}"
        api_version: v1
        kind: ConfigMap
        name: thinkube-service-config-grafana
        namespace: monitoring
      register: grafana_configmap

    - name: Display ConfigMap status
      ansible.builtin.debug:
        msg: 
          - "Monitoring ConfigMap (for Optional Components): {{ 'Created' if monitoring_configmap.resources | length > 0 else 'Failed' }}"
          - "Prometheus ConfigMap (for Dashboard): {{ 'Created' if prometheus_configmap.resources | length > 0 else 'Failed' }}"
          - "Grafana ConfigMap (for Dashboard): {{ 'Created' if grafana_configmap.resources | length > 0 else 'Failed' }}"