# Copyright 2025 Alejandro Martínez Corriá and the Thinkube contributors
# SPDX-License-Identifier: Apache-2.0

---
# ansible/40_thinkube/core/harbor/11_install_podman.yaml
# Description:
#   Installs and configures podman for registry testing
#   Enables rootless podman for the current user
#   Installs QEMU for multi-architecture builds (amd64/arm64)
#
# Requirements:
#   - Ubuntu/Debian-based system
#   - Sudo privileges for package installation
#
# Usage:
#   cd ~/thinkube
#   ./scripts/run_ansible.sh ansible/40_thinkube/core/harbor/11_install_podman.yaml
#
# Variables from inventory:
#   - system_username: System user to configure podman for
#
# 🤖 [AI-assisted]

- name: Install and Configure Podman
  hosts: microk8s_control_plane
  gather_facts: true

  tasks:
    ##########################################################################
    # Install Podman
    ##########################################################################

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
      become: true
      when: ansible_os_family == "Debian"

    - name: Install podman packages
      ansible.builtin.apt:
        name:
          - podman
          - podman-compose
          - podman-toolbox
          - buildah
          - skopeo
          - qemu-user-static
          - binfmt-support
        state: present
      become: true
      when: ansible_os_family == "Debian"

    - name: Enable QEMU binfmt support for multi-arch builds
      ansible.builtin.systemd:
        name: systemd-binfmt.service
        state: restarted
        enabled: yes
      become: true
      when: ansible_os_family == "Debian"

    - name: Verify QEMU handlers are registered
      ansible.builtin.shell: |
        ls -la /proc/sys/fs/binfmt_misc/ | grep -E '(qemu-aarch64|qemu-arm)' || echo "No ARM handlers found"
      register: qemu_handlers
      changed_when: false
      failed_when: false

    - name: Display QEMU multi-arch status
      ansible.builtin.debug:
        msg:
          - "QEMU multi-architecture support:"
          - "{{ qemu_handlers.stdout_lines }}"
          - "Multi-arch builds (amd64/arm64) are now supported"

    - name: Ensure user can use podman rootless
      ansible.builtin.user:
        name: "{{ system_username }}"
        groups:
          - systemd-journal
        append: yes
      become: true

    - name: Enable and start user systemd service
      ansible.builtin.shell: |
        loginctl enable-linger {{ system_username }}
      become: true
      changed_when: false

    - name: Create podman directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ system_username }}"
        group: "{{ system_username }}"
        mode: '0700'
      with_items:
        - "/home/{{ system_username }}/.config/containers"
        - "/home/{{ system_username }}/.local/share/containers"
      become: true

    - name: Configure podman registries for user
      ansible.builtin.copy:
        content: |
          unqualified-search-registries = ["{{ harbor_registry }}"]

          [[registry]]
          location = "{{ harbor_registry }}"
          insecure = false

          [[registry]]
          location = "docker.io"

          [[registry]]
          location = "quay.io"

          [[registry]]
          location = "ghcr.io"
        dest: "/home/{{ system_username }}/.config/containers/registries.conf"
        owner: "{{ system_username }}"
        group: "{{ system_username }}"
        mode: '0644'
      become: true

    - name: Configure system-wide podman registries
      ansible.builtin.copy:
        content: |
          unqualified-search-registries = ["{{ harbor_registry }}"]

          [[registry]]
          location = "{{ harbor_registry }}"
          insecure = false

          [[registry]]
          location = "docker.io"

          [[registry]]
          location = "quay.io"

          [[registry]]
          location = "ghcr.io"
        dest: "/etc/containers/registries.conf"
        mode: '0644'
      become: true

    - name: Set subuid and subgid mappings
      ansible.builtin.lineinfile:
        path: "{{ item.path }}"
        regexp: "^{{ system_username }}:"
        line: "{{ system_username }}:100000:65536"
        create: yes
      with_items:
        - { path: /etc/subuid }
        - { path: /etc/subgid }
      become: true

    - name: Initialize podman system
      ansible.builtin.shell: |
        cd /tmp && podman system migrate
      become: false
      changed_when: false

    - name: Verify podman installation
      ansible.builtin.command: podman version
      register: podman_version
      changed_when: false

    - name: Display podman version
      ansible.builtin.debug:
        var: podman_version.stdout_lines

    - name: Test podman with hello-world
      ansible.builtin.shell: |
        cd /tmp && podman run --rm hello-world
      register: podman_test
      changed_when: false
      failed_when: false
      become: false

    - name: Display podman test result
      ansible.builtin.debug:
        msg:
          - "Podman installed successfully"
          - "Version: {{ podman_version.stdout_lines[0] | default('Unknown') }}"
          - "Test result: {{ 'PASSED' if podman_test.rc == 0 else 'FAILED' }}"