# Copyright 2025 Alejandro Martínez Corriá and the Thinkube contributors
# SPDX-License-Identifier: Apache-2.0

---
# Core Shell Setup - Install required packages and create directory structure
- name: Update apt cache
  become: true
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"
  tags: [packages]

- name: Check for required packages
  shell: command -v {{ item }} || echo "not installed"
  register: package_check
  loop: "{{ required_packages }}"
  changed_when: false
  tags: [packages]

- name: Show warning about missing packages
  ansible.builtin.debug:
    msg: "Warning: The following packages may be missing: {{ missing_packages|join(', ') }}. These are required for the playbook to work properly. Please install them manually."
  vars:
    missing_packages: "{{ package_check.results | selectattr('stdout', 'search', 'not installed') | map(attribute='item') | list }}"
  when: missing_packages | length > 0
  tags: [packages]

- name: Attempt to install required packages (if sudo is available)
  become: yes
  package:
    name: "{{ required_packages }}"
    state: present
  register: package_install
  ignore_errors: yes
  tags: [packages]

- name: Ensure clean function and alias directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ thinkube_system_dir }}"
    - "{{ thinkube_system_functions_dir }}"
    - "{{ thinkube_system_docs_dir }}"
    - "{{ thinkube_system_aliases_dir }}"
    - "{{ thinkube_user_dir }}"
    - "{{ thinkube_user_functions_dir }}"
    - "{{ thinkube_user_aliases_dir }}"
  tags: [thinkube, setup]