# Copyright 2025 Alejandro Martínez Corriá and the Thinkube contributors
# SPDX-License-Identifier: Apache-2.0

---
# Fish Plugins Setup - Fisher plugin manager and useful extensions

# Install Fisher (Fisher plugin manager) with simplified approach
- name: Create fish functions directory 
  file:
    path: "{{ fish_config_dir }}/functions"
    state: directory
    mode: '0755'

# We know fish exists on all systems - directly set its path
- name: Set fish binary path
  set_fact:
    fish_binary: "/usr/bin/fish"
  tags: [fish, plugins]

- name: Debug fish binary path
  debug:
    msg: "Fish binary: {{ fish_binary }}"
    verbosity: 0

- name: Download Fisher plugin manager file
  get_url:
    url: https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish
    dest: "{{ fish_config_dir }}/functions/fisher.fish"
    mode: '0644'
  register: fisher_download
  tags: [fish, plugins]

# Check if fish_plugins file exists and has content
- name: Check fish_plugins file status
  stat:
    path: "{{ fish_config_dir }}/fish_plugins"
  register: fish_plugins_stat
  tags: [fish, plugins]

# Create fish_plugins file with our desired plugins if it doesn't exist or is empty
- name: Create fish_plugins file with default plugins
  copy:
    content: |
      edc/bass
      PatrickF1/fzf.fish
      franciscolourenco/done
      jorgebucaran/autopair.fish
    dest: "{{ fish_config_dir }}/fish_plugins"
    mode: '0644'
  when: not fish_plugins_stat.stat.exists or fish_plugins_stat.stat.size == 0
  tags: [fish, plugins]

# Now update/install plugins from fish_plugins file
- name: Initialize Fisher plugin manager
  shell: "{{ fish_binary }} -c 'fisher update'"
  register: fisher_init
  changed_when: "'Updated' in fisher_init.stdout"
  environment:
    TERM: dumb
    NONINTERACTIVE: 1
  tags: [fish, plugins]

# Now list installed plugins
- name: List installed plugins
  command: "{{ fish_binary }} -c 'fisher list'"
  register: plugin_list
  changed_when: false
  environment:
    TERM: dumb
    NONINTERACTIVE: 1
  tags: [fish, plugins]

- name: Display current plugins
  debug:
    var: plugin_list.stdout_lines
  tags: [fish, plugins]

- name: Install Fish plugins directly
  command: "{{ fish_binary }} -c 'fisher install {{ item }}'"
  register: plugin_install
  loop: "{{ fisher_plugins }}"
  changed_when: "'Installing' in plugin_install.stdout"
  environment:
    TERM: dumb
    NONINTERACTIVE: 1
  tags: [fish, plugins]
  
- name: Final plugin list after installation
  command: "{{ fish_binary }} -c 'fisher list'"
  register: final_plugin_list
  changed_when: false
  environment:
    TERM: dumb
    NONINTERACTIVE: 1
  tags: [fish, plugins]
  
- name: Display installed plugins
  debug:
    var: final_plugin_list.stdout_lines
  tags: [fish, plugins]