# Copyright 2025 Alejandro Martínez Corriá and the Thinkube contributors
# SPDX-License-Identifier: Apache-2.0

---
# ansible/40_thinkube/core/keycloak/00_install.yaml
# Description:
#   Orchestrator playbook that runs all Keycloak component playbooks in sequence
#   This simplifies the installer by providing a single entry point
#
# Requirements:
#   - MicroK8s must be installed and running
#   - PostgreSQL must be deployed
#   - Ingress controller must be deployed
#
# Usage:
#   cd ~/thinkube
#   ./scripts/run_ansible.sh ansible/40_thinkube/core/keycloak/00_install.yaml
#
# Variables from inventory:
#   - All variables required by individual playbooks
#

- name: Keycloak - Deploy
  import_playbook: 10_deploy.yaml
  
- name: Keycloak - Configure Realm
  import_playbook: 15_configure_realm.yaml
  
- name: Keycloak - Configure Theme
  import_playbook: 16_configure_theme.yaml
  
- name: Keycloak - Configure Service Discovery
  import_playbook: 17_configure_discovery.yaml