# Copyright 2025 Alejandro Martínez Corriá and the Thinkube contributors
# SPDX-License-Identifier: Apache-2.0

---
# Test admin authentication after deployment
- name: Test Keycloak Admin Authentication
  hosts: microk8s_control_plane
  gather_facts: false
  
  vars:
    admin_password: "{{ lookup('env', 'ADMIN_PASSWORD') | default(lookup('env', 'ANSIBLE_BECOME_PASSWORD'), true) }}"
    
  tasks:
    - name: Display authentication info
      ansible.builtin.debug:
        msg: |
          Testing authentication with:
          URL: {{ keycloak_url }}/realms/master/protocol/openid-connect/token
          Username: {{ admin_username }}
          Admin email: {{ admin_email }}
          
    - name: Test default admin authentication
      ansible.builtin.uri:
        url: "{{ keycloak_url }}/realms/master/protocol/openid-connect/token"
        method: POST
        body_format: form-urlencoded
        body:
          client_id: "admin-cli"
          username: "admin"
          password: "{{ admin_password }}"
          grant_type: "password"
        validate_certs: no  # Temporarily disabled
        status_code: [200, 401]
      register: default_auth_result
      
    - name: Test new admin authentication
      ansible.builtin.uri:
        url: "{{ keycloak_url }}/realms/master/protocol/openid-connect/token"
        method: POST
        body_format: form-urlencoded
        body:
          client_id: "admin-cli"
          username: "{{ admin_username }}"
          password: "{{ admin_password }}"
          grant_type: "password"
        validate_certs: no  # Temporarily disabled
        status_code: [200, 401]
      register: new_auth_result
      
    - name: Display authentication results
      ansible.builtin.debug:
        msg: |
          Default admin authentication:
          Status: {{ default_auth_result.status }}
          {% if default_auth_result.status == 401 %}
          Error: {{ default_auth_result.json.error_description | default('Unknown error') }}
          {% else %}
          Success! Token received.
          {% endif %}
          
          New admin authentication:
          Status: {{ new_auth_result.status }}
          {% if new_auth_result.status == 401 %}
          Error: {{ new_auth_result.json.error_description | default('Unknown error') }}
          {% else %}
          Success! Token received.
          {% endif %}