# Copyright 2025 Alejandro Martínez Corriá and the Thinkube contributors
# SPDX-License-Identifier: Apache-2.0

---
# ansible/40_thinkube/core/thinkube-control/00_install.yaml
# Description:
#   Orchestrator playbook that runs all thinkube-control component playbooks in sequence
#   This simplifies the installer by providing a single entry point
#
# Requirements:
#   - MicroK8s must be installed and running
#   - Keycloak must be deployed and configured
#   - ArgoCD must be deployed (for webhook integration)
#   - Gitea must be deployed (for GitOps workflow)
#
# Usage:
#   cd ~/thinkube
#   ./scripts/run_ansible.sh ansible/40_thinkube/core/thinkube-control/00_install.yaml
#
# Variables from inventory:
#   - All variables required by individual playbooks
#
# 🤖 [AI-assisted]

- name: Thinkube Control - Deploy Sync Webhook
  import_playbook: 10_deploy_sync_webhook.yaml
  
- name: Thinkube Control - Deploy Webhook Adapter
  import_playbook: 11_deploy_webhook_adapter.yaml
  
- name: Thinkube Control - Deploy
  import_playbook: 12_deploy.yaml
  
- name: Thinkube Control - Configure Code Server
  import_playbook: 13_configure_code_server.yaml

- name: Thinkube Control - Deploy tk-package-version MCP server
  import_playbook: 14_deploy_tk_package_version.yaml