# Copyright 2025 Alejandro Martínez Corriá and the Thinkube contributors
# SPDX-License-Identifier: Apache-2.0

---
- name: restart containerd
  ansible.builtin.systemd:
    name: containerd
    state: restarted
    daemon_reload: true
  become: true
