# Copyright 2025 Alejandro Martínez Corriá and the Thinkube contributors
# SPDX-License-Identifier: Apache-2.0

---
# SeaweedFS PersistentVolume for JupyterHub notebooks
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jupyter-notebooks-pv
  labels:
    app: jupyterhub
    type: notebooks
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany  # Critical - allows access from multiple nodes
  persistentVolumeReclaimPolicy: Retain
  storageClassName: seaweedfs-storage
  csi:
    driver: seaweedfs-csi
    volumeHandle: jupyter-notebooks
    fsType: ext4
    volumeAttributes:
      collection: "jupyter"
      replication: "001"  # Single replica for home use
---
# PersistentVolumeClaim for JupyterHub notebooks
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyter-notebooks-pvc
  namespace: jupyterhub
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: seaweedfs-storage
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      app: jupyterhub
      type: notebooks
---
# PersistentVolume for large datasets
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jupyter-datasets-pv
  labels:
    app: jupyterhub
    type: datasets
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: seaweedfs-storage
  csi:
    driver: seaweedfs-csi
    volumeHandle: jupyter-datasets
    fsType: ext4
    volumeAttributes:
      collection: "datasets"
      replication: "001"
---
# PersistentVolumeClaim for datasets
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyter-datasets-pvc
  namespace: jupyterhub
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: seaweedfs-storage
  resources:
    requests:
      storage: 200Gi
  selector:
    matchLabels:
      app: jupyterhub
      type: datasets
---
# PersistentVolume for trained models
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jupyter-models-pv
  labels:
    app: jupyterhub
    type: models
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: seaweedfs-storage
  csi:
    driver: seaweedfs-csi
    volumeHandle: jupyter-models
    fsType: ext4
    volumeAttributes:
      collection: "models"
      replication: "001"
---
# PersistentVolumeClaim for models
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyter-models-pvc
  namespace: jupyterhub
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: seaweedfs-storage
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      app: jupyterhub
      type: models