name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        # Core Components
        - "Core - Argo Workflows (CI/CD)"
        - "Core - ArgoCD (GitOps)"
        - "Core - Code Server (VS Code)"
        - "Core - DevPi (Python Cache)"
        - "Core - Gitea (Git Server)"
        - "Core - GPU Operator"
        - "Core - Harbor (Container Registry)"
        - "Core - Harbor Base Images"
        - "Core - Infrastructure (Ingress, Certs)"
        - "Core - JuiceFS (Shared Storage)"
        - "Core - JupyterHub"
        - "Core - Keycloak (Authentication)"
        - "Core - MLflow (Model Registry)"
        - "Core - PostgreSQL (Database)"
        - "Core - SeaweedFS (Object Storage)"
        - "Core - Thinkube Control (Dashboard)"
        # Optional Components
        - "Optional - Argilla (Data Labeling)"
        - "Optional - Chroma (Vector DB)"
        - "Optional - ClickHouse (Analytics DB)"
        - "Optional - CVAT (Image Annotation)"
        - "Optional - Knative (Serverless)"
        - "Optional - Langfuse (LLM Observability)"
        - "Optional - LiteLLM (LLM Gateway)"
        - "Optional - NATS (Messaging)"
        - "Optional - Ollama (Local LLMs)"
        - "Optional - OpenSearch (Search Engine)"
        - "Optional - Perses (Dashboards)"
        - "Optional - pgAdmin (DB Admin)"
        - "Optional - Prometheus (Metrics)"
        - "Optional - Qdrant (Vector DB)"
        - "Optional - Valkey (Cache)"
        - "Optional - Weaviate (Vector DB)"
        # Other
        - "Installer (Desktop App)"
        - "Template - vLLM Gradio"
        - "Template - TensorRT-LLM"
        - "Template - Text Embeddings"
        - "Template - Web App (Vue+FastAPI)"
        - "Other / Not Sure"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? Please be as detailed as possible.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: false

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Deploy component X with...
        2. Navigate to...
        3. Click on...
        4. See error...
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Please paste any relevant log output (will be automatically formatted as code)
      render: shell
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide system details
      placeholder: |
        - OS: Ubuntu 24.04
        - Architecture: arm64 / amd64
        - GPU: DGX Spark / RTX 4090 / None
        - Thinkube version: 0.1.0
        - Kubernetes: k8s-snap / microk8s
    validations:
      required: false
