name: Documentation
description: Report missing, incorrect, or unclear documentation
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: dropdown
    id: type
    attributes:
      label: Documentation Type
      description: What kind of documentation issue is this?
      options:
        - "Missing documentation"
        - "Incorrect or outdated information"
        - "Unclear or confusing instructions"
        - "Typo or formatting issue"
        - "Missing example or tutorial"
    validations:
      required: true

  - type: dropdown
    id: location
    attributes:
      label: Documentation Location
      description: Where is this documentation located?
      options:
        - "thinkube.org website"
        - "README file"
        - "CLAUDE.md file"
        - "Inline code comments"
        - "Deployment guide"
        - "API documentation"
        - "Other / New documentation needed"
    validations:
      required: true

  - type: input
    id: url
    attributes:
      label: URL or File Path
      description: Link to the page or file path (if applicable)
      placeholder: "https://thinkube.org/... or ansible/40_thinkube/core/.../README.md"
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be fixed, added, or clarified?
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Fix
      description: If you have a suggestion for how to fix this, please share it
    validations:
      required: false
