name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this affect?
      options:
        # Core Components
        - "Core - Argo Workflows (CI/CD)"
        - "Core - ArgoCD (GitOps)"
        - "Core - Code Server (VS Code)"
        - "Core - DevPi (Python Cache)"
        - "Core - Gitea (Git Server)"
        - "Core - GPU Operator"
        - "Core - Harbor (Container Registry)"
        - "Core - Harbor Base Images"
        - "Core - Infrastructure (Ingress, Certs)"
        - "Core - JuiceFS (Shared Storage)"
        - "Core - JupyterHub"
        - "Core - Keycloak (Authentication)"
        - "Core - MLflow (Model Registry)"
        - "Core - PostgreSQL (Database)"
        - "Core - SeaweedFS (Object Storage)"
        - "Core - Thinkube Control (Dashboard)"
        # Optional Components
        - "Optional - Argilla (Data Labeling)"
        - "Optional - Chroma (Vector DB)"
        - "Optional - ClickHouse (Analytics DB)"
        - "Optional - CVAT (Image Annotation)"
        - "Optional - Knative (Serverless)"
        - "Optional - Langfuse (LLM Observability)"
        - "Optional - LiteLLM (LLM Gateway)"
        - "Optional - NATS (Messaging)"
        - "Optional - Ollama (Local LLMs)"
        - "Optional - OpenSearch (Search Engine)"
        - "Optional - Perses (Dashboards)"
        - "Optional - pgAdmin (DB Admin)"
        - "Optional - Prometheus (Metrics)"
        - "Optional - Qdrant (Vector DB)"
        - "Optional - Valkey (Cache)"
        - "Optional - Weaviate (Vector DB)"
        # Other
        - "Installer (Desktop App)"
        - "Template - vLLM Gradio"
        - "Template - TensorRT-LLM"
        - "Template - Text Embeddings"
        - "Template - Web App (Vue+FastAPI)"
        - "New Component"
        - "Multiple Components"
        - "Other / Not Sure"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Why is it needed?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative approaches?
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or references?
    validations:
      required: false
