# Copyright 2025 Alejandro Martínez Corriá and the Thinkube contributors
# SPDX-License-Identifier: Apache-2.0

---
# ansible/40_thinkube/optional/jupyterhub/00_install.yaml
# Description:
#   Orchestrator playbook that runs all JupyterHub component playbooks in sequence
#   This simplifies installation by providing a single entry point
#
# Requirements:
#   - MicroK8s must be installed and running
#   - Keycloak must be deployed
#   - Harbor registry must be deployed
#
# Usage:
#   cd ~/thinkube
#   ./scripts/run_ansible.sh ansible/40_thinkube/optional/jupyterhub/00_install.yaml
#
# Variables from inventory:
#   - All variables required by individual playbooks
#

- name: JupyterHub - Build Custom Images
  import_playbook: 10_build_images.yaml
  
- name: JupyterHub - Configure Keycloak
  import_playbook: 11_configure_keycloak.yaml
  
- name: JupyterHub - Deploy
  import_playbook: 12_deploy.yaml
  
- name: JupyterHub - Configure Service Discovery
  import_playbook: 17_configure_discovery.yaml