# Copyright 2025 Alejandro Martínez Corriá and the Thinkube contributors
# SPDX-License-Identifier: Apache-2.0

---
# ansible/40_thinkube/optional/perses/00_install.yaml
# Description:
#   Orchestrator playbook for complete Perses deployment
#
# This playbook executes all Perses deployment steps in sequence:
#   1. Configure Keycloak OIDC client
#   2. Deploy Perses using Helm chart
#   3. Import community dashboards using percli
#   4. Configure service discovery
#
# Requirements:
#   - Kubernetes (k8s-snap) must be installed and running
#   - Keycloak must be deployed
#   - Prometheus must be deployed
#   - ADMIN_PASSWORD environment variable must be set
#
# Usage:
#   cd ~/thinkube
#   ./scripts/tk_ansible ansible/40_thinkube/optional/perses/00_install.yaml
#
# Note: Tests (18_test.yaml) are run separately, not part of installation
#
# 🤖 AI-assisted

- import_playbook: 10_configure_keycloak.yaml
- import_playbook: 11_deploy.yaml
- import_playbook: 14_import_dashboards_percli.yaml
- import_playbook: 17_configure_discovery.yaml
