# Copyright 2025 Alejandro Martínez Corriá and the Thinkube contributors
# SPDX-License-Identifier: Apache-2.0

# Thinkube custom values for Perses Helm chart
# This file is processed as an Ansible template

# Perses configuration
config:
  security:
    # Enable authentication
    enable_auth: true
    cookie:
      same_site: lax
      secure: true  # HTTPS is used
    # Enable native provider for API access
    authentication:
      providers:
        enable_native: true
    # Grant full admin permissions to all logged-in users (guest_permissions)
    # This allows the initial admin user to create GlobalRoles and GlobalRoleBindings
    authorization:
      guest_permissions:
        - actions: ["*"]
          scopes: ["*"]

  frontend:
    explorer:
      enable: true

# OIDC Authentication via environment variables
# Perses uses PERSES_<YAML_PATH> pattern for env var config
envVars:
  - name: PERSES_SECURITY_AUTHENTICATION_PROVIDERS_OIDC_0_SLUG_ID
    value: "keycloak"
  - name: PERSES_SECURITY_AUTHENTICATION_PROVIDERS_OIDC_0_NAME
    value: "Keycloak SSO"
  - name: PERSES_SECURITY_AUTHENTICATION_PROVIDERS_OIDC_0_CLIENT_ID
    value: "{{ perses_client_id }}"
  - name: PERSES_SECURITY_AUTHENTICATION_PROVIDERS_OIDC_0_CLIENT_SECRET
    value: "{{ keycloak_client_secret }}"
  - name: PERSES_SECURITY_AUTHENTICATION_PROVIDERS_OIDC_0_ISSUER
    value: "{{ keycloak_url }}/realms/{{ keycloak_realm }}"
  - name: PERSES_SECURITY_AUTHENTICATION_PROVIDERS_OIDC_0_REDIRECT_URI
    value: "https://{{ perses_hostname }}/api/auth/providers/oidc/keycloak/callback"
  - name: PERSES_SECURITY_AUTHENTICATION_PROVIDERS_OIDC_0_SCOPES_0
    value: "openid"
  - name: PERSES_SECURITY_AUTHENTICATION_PROVIDERS_OIDC_0_SCOPES_1
    value: "profile"
  - name: PERSES_SECURITY_AUTHENTICATION_PROVIDERS_OIDC_0_SCOPES_2
    value: "email"
  - name: PERSES_SECURITY_AUTHENTICATION_PROVIDERS_OIDC_0_SCOPES_3
    value: "roles"

# Ingress configuration
ingress:
  enabled: true
  ingressClassName: "{{ primary_ingress_class }}"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: "{{ perses_hostname }}"
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: "{{ perses_tls_secret_name }}"
      hosts:
        - "{{ perses_hostname }}"

# Resource limits
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Enable persistence for dashboards (uses file database)
persistence:
  enabled: true
  size: 1Gi
  accessModes:
    - ReadWriteOnce

# Enable sidecar to load dashboards from ConfigMaps
sidecar:
  enabled: true
  label: "perses.dev/resource"
  labelValue: "true"
  # Skip SSL verification for Kubernetes API (k8s-snap self-signed certs)
  extraEnvVars:
    - name: SKIP_TLS_VERIFY
      value: "true"
