# Copyright 2025 Alejandro Martínez Corriá and the Thinkube contributors
# SPDX-License-Identifier: Apache-2.0

---
# ansible/40_thinkube/optional/langfuse/00_install.yaml
# Description:
#   Orchestrator playbook for Langfuse deployment
#   Installs Langfuse LLM observability platform with PostgreSQL and OIDC
#
# Requirements:
#   - Kubernetes (k8s-snap) must be installed
#   - PostgreSQL must be deployed
#   - Keycloak must be deployed
#   - ADMIN_PASSWORD environment variable set
#
# Usage:
#   cd ~/thinkube
#   ./scripts/run_ansible.sh ansible/40_thinkube/optional/langfuse/00_install.yaml
#
# Variables from inventory:
#   - domain_name: Base domain name
#   - kubeconfig: Path to kubeconfig file
#   - harbor_registry: Harbor registry URL
#
# Dependencies:
#   - CORE-005: PostgreSQL must be deployed
#   - CORE-006: Keycloak must be deployed
#
# 🤖 [AI-assisted]

- name: Langfuse - Configure Keycloak OIDC
  import_playbook: 10_configure_keycloak.yaml

- name: Langfuse - Deploy
  import_playbook: 11_deploy.yaml

- name: Langfuse - Configure Service Discovery
  import_playbook: 17_configure_discovery.yaml
