---
# ansible/40_thinkube/optional/clickhouse/00_install.yaml
# Description:
#   Orchestrator playbook for ClickHouse installation
#   Deploys ClickHouse analytics database for CVAT and other services
#
# Requirements:
#   - MicroK8s must be installed and running
#   - Helm must be available
#   - ADMIN_PASSWORD environment variable must be set
#
# Usage:
#   cd ~/thinkube
#   ./scripts/run_ansible.sh ansible/40_thinkube/optional/clickhouse/00_install.yaml
#
# 🤖 [AI-generated]

- name: ClickHouse - Deploy
  import_playbook: 10_deploy.yaml

- name: ClickHouse - Configure Service Discovery
  import_playbook: 17_configure_discovery.yaml