---
# ansible/40_thinkube/optional/clickhouse/19_rollback.yaml
# Description:
#   Rollback/uninstall playbook for ClickHouse
#   Removes all ClickHouse resources from the cluster
#
# Requirements:
#   - MicroK8s must be installed and running
#
# Usage:
#   cd ~/thinkube
#   ./scripts/run_ansible.sh ansible/40_thinkube/optional/clickhouse/19_rollback.yaml
#
# 🤖 [AI-generated]

- name: Rollback ClickHouse deployment
  hosts: microk8s_control_plane
  gather_facts: true

  vars:
    clickhouse_namespace: clickhouse

  tasks:
    - name: Verify kubeconfig is defined
      ansible.builtin.assert:
        that:
          - kubeconfig is defined
        fail_msg: "kubeconfig is not defined"

    - name: Delete ClickHouse namespace (deletes everything)
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        name: "{{ clickhouse_namespace }}"
        api_version: v1
        kind: Namespace
        state: absent
        wait: false

    - name: Display rollback status
      ansible.builtin.debug:
        msg:
          - "ClickHouse namespace deletion initiated"
          - "All resources in the {{ clickhouse_namespace }} namespace will be deleted"