# Copyright 2025 Alejandro Martínez Corriá and the Thinkube contributors
# SPDX-License-Identifier: Apache-2.0

---
# ansible/40_thinkube/optional/qdrant/00_install.yaml
# Description:
#   Orchestrator playbook that runs all Qdrant component playbooks in sequence
#   This installs Qdrant vector database for AI/ML applications
#
# Requirements:
#   - MicroK8s must be installed and running
#   - Ingress controller must be deployed
#
# Usage:
#   cd ~/thinkube
#   ./scripts/run_ansible.sh ansible/40_thinkube/optional/qdrant/00_install.yaml
#
# Variables from inventory:
#   - All variables required by individual playbooks
#

- name: Qdrant - Deploy
  import_playbook: 10_deploy.yaml
  
- name: Qdrant - Configure Service Discovery
  import_playbook: 17_configure_discovery.yaml