# Copyright 2025 Alejandro Martínez Corriá and the Thinkube contributors
# SPDX-License-Identifier: Apache-2.0

---
# ansible/40_thinkube/optional/qdrant/17_configure_discovery.yaml
# Description:
#   Configure service discovery for Qdrant by creating a ConfigMap
#   that describes the service endpoints and metadata
#
# Requirements:
#   - Qdrant must be deployed
#   - MicroK8s kubectl access
#
# Usage:
#   cd ~/thinkube
#   ./scripts/run_ansible.sh ansible/40_thinkube/optional/qdrant/17_configure_discovery.yaml
#
# Variables from inventory:
#   - domain_name: Base domain for the cluster
#   - kubeconfig: Path to kubeconfig file

- name: Configure Qdrant service discovery
  hosts: microk8s_control_plane
  gather_facts: true
  
  tasks:
    - name: Create service discovery ConfigMap
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        state: present
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: thinkube-service-config
            namespace: qdrant
            labels:
              thinkube.io/managed: "true"
              thinkube.io/service-type: "optional"
              thinkube.io/service-name: "qdrant"
          data:
            service.yaml: |
              service:
                name: qdrant
                display_name: "Qdrant"
                description: "Vector database for AI applications"
                type: optional
                category: ai
                icon: /icons/tk_vector.svg
                
                endpoints:
                  - name: web
                    type: http
                    url: "https://qdrant.{{ domain_name }}"
                    health_url: "https://qdrant.{{ domain_name }}/"
                    description: "Web interface"
                    primary: true
                    
                dependencies: []
                  
                scaling:
                  resource_type: statefulset
                  resource_name: qdrant
                  namespace: qdrant
                  min_replicas: 1
                  can_disable: true
                  
    - name: Verify ConfigMap creation
      kubernetes.core.k8s_info:
        kubeconfig: "{{ kubeconfig }}"
        api_version: v1
        kind: ConfigMap
        name: thinkube-service-config
        namespace: qdrant
      register: configmap_info
      
    - name: Display ConfigMap status
      ansible.builtin.debug:
        msg: "Service discovery ConfigMap created for Qdrant"
      when: configmap_info.resources | length > 0
