# Copyright 2025 Alejandro Martínez Corriá and the Thinkube contributors
# SPDX-License-Identifier: Apache-2.0

---
# ansible/40_thinkube/optional/qdrant/19_rollback.yaml
# Description:
#   Rollback Qdrant deployment and clean up all resources
#
# Requirements:
#   - MicroK8s must be installed
#   - kubectl access configured
#
# Usage:
#   cd ~/thinkube
#   ./scripts/run_ansible.sh ansible/40_thinkube/optional/qdrant/19_rollback.yaml
#
# Variables from inventory:
#   - kubeconfig: Path to kubectl configuration
#   - kubectl_bin: Path to kubectl binary
#   - helm_bin: Path to helm binary
#   - qdrant_namespace: Namespace for Qdrant
#
# 🤖 [AI-assisted]

- name: Rollback Qdrant deployment
  hosts: microk8s_control_plane
  gather_facts: true

  vars:
    k8s_namespace: "{{ qdrant_namespace }}"

  tasks:
    - name: Delete Qdrant namespace (and all resources within)
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        state: absent
        kind: Namespace
        name: "{{ k8s_namespace }}"
      failed_when: false

    - name: Remove Qdrant Helm repository
      kubernetes.core.helm_repository:
        binary_path: "{{ helm_bin }}"
        name: qdrant
        state: absent
      failed_when: false

    - name: Display rollback completion
      ansible.builtin.debug:
        msg:
          - "Qdrant rollback completed"
          - "-----------------------------------"
          - "Removed namespace: {{ k8s_namespace }}"
          - "Removed Helm repository: qdrant"
          - "-----------------------------------"