# Copyright 2025 Alejandro Martínez Corriá and the Thinkube contributors
# SPDX-License-Identifier: Apache-2.0

---
# ansible/40_thinkube/core/postgresql/00_install.yaml
# Description:
#   Orchestrator playbook that runs all PostgreSQL component playbooks in sequence
#   This simplifies the installer by providing a single entry point
#
# Requirements:
#   - MicroK8s must be installed and running
#   - Ingress controller must be deployed
#
# Usage:
#   cd ~/thinkube
#   ./scripts/run_ansible.sh ansible/40_thinkube/core/postgresql/00_install.yaml
#
# Variables from inventory:
#   - All variables required by individual playbooks
#

- name: PostgreSQL - Deploy
  import_playbook: 10_deploy.yaml
  
- name: PostgreSQL - Configure Service Discovery
  import_playbook: 17_configure_discovery.yaml