parent=base
import=common/keycloak

# Theme configuration
styles=css/login.css
stylesCommon=
scripts=js/terrain-bg.js js/password-toggle.js

# Disable PatternFly
kcLoginClass=
kcFormClass=
kcFormCardClass=
kcFormHeaderClass=

# Localization
locales=en