# Copyright 2025 Alejandro Martínez Corriá and the Thinkube contributors
# SPDX-License-Identifier: Apache-2.0

---
# ansible/40_thinkube/optional/weaviate/00_install.yaml
# Description:
#   Orchestrator playbook for Weaviate vector database installation
#   This playbook calls the individual playbooks in the correct order
#
# Requirements:
#   - MicroK8s must be installed and running
#   - ADMIN_PASSWORD environment variable must be set
#
# Usage:
#   cd ~/thinkube
#   ./scripts/run_ansible.sh ansible/40_thinkube/optional/weaviate/00_install.yaml
#
# 🤖 AI-assisted

- name: Install Weaviate Vector Database
  hosts: microk8s_control_plane
  gather_facts: false

  tasks:
    - name: Deploy Weaviate
      ansible.builtin.include_tasks:
        file: 10_deploy.yaml
        apply:
          tags: always

    - name: Configure service discovery
      ansible.builtin.include_tasks:
        file: 17_configure_discovery.yaml
        apply:
          tags: always

    - name: Installation complete
      ansible.builtin.debug:
        msg: |
          Weaviate vector database has been successfully installed!

          Access the API at: https://weaviate.{{ domain_name }}

          Authentication: API key based (using admin credentials)

          To test the installation:
          ./scripts/run_ansible.sh ansible/40_thinkube/optional/weaviate/18_test.yaml