# Copyright 2025 Alejandro Martínez Corriá and the Thinkube contributors
# SPDX-License-Identifier: Apache-2.0

---
# ansible/40_thinkube/optional/prometheus/00_install.yaml
# Description:
#   Complete installation of Prometheus Operator with kube-prometheus stack
#
# This playbook orchestrates:
#   1. Tool installation (Go, jsonnet, jb, gojsontoyaml, percli)
#   2. Prometheus Operator deployment with kubernetes-mixin recording rules
#   3. Service discovery registration
#
# Requirements:
#   - Kubernetes (k8s-snap) must be installed and running
#   - Internet access to download tools and dependencies
#   - sudo access on control plane node
#   - thinkube-control must be deployed (for service discovery)
#
# Usage:
#   cd ~/thinkube
#   ./scripts/tk_ansible ansible/40_thinkube/optional/prometheus/00_install.yaml
#
# Variables from inventory:
#   - kubeconfig: Path to kubeconfig file
#   - domain_name: Base domain for ingress
#
# 🤖 AI-assisted

- name: Prometheus Operator - Install Tools
  ansible.builtin.import_playbook: 10_install_tools.yaml

- name: Prometheus Operator - Deploy
  ansible.builtin.import_playbook: 11_deploy.yaml

- name: Prometheus Operator - Configure Service Discovery
  ansible.builtin.import_playbook: 17_service_discovery.yaml
