# Copyright 2025 Alejandro Martínez Corriá and the Thinkube contributors
# SPDX-License-Identifier: Apache-2.0

---
tier_limits:
  critical:
    limit_range_default_memory: "4Gi"
    limit_range_default_cpu: "2"
    limit_range_default_request_memory: "128Mi"
    limit_range_default_request_cpu: "50m"
    quota_requests_memory: "16Gi"
    quota_limits_memory: "32Gi"
    quota_requests_cpu: "4"
    quota_limits_cpu: "8"
  platform:
    limit_range_default_memory: "4Gi"
    limit_range_default_cpu: "2"
    limit_range_default_request_memory: "128Mi"
    limit_range_default_request_cpu: "50m"
    quota_requests_memory: "16Gi"
    quota_limits_memory: "32Gi"
    quota_requests_cpu: "4"
    quota_limits_cpu: "8"
  workload:
    limit_range_default_memory: "256Mi"
    limit_range_default_cpu: "250m"
    limit_range_default_request_memory: "64Mi"
    limit_range_default_request_cpu: "25m"
    quota_requests_memory: "8Gi"
    quota_limits_memory: "16Gi"
    quota_requests_cpu: "4"
    quota_limits_cpu: "8"
  batch:
    limit_range_default_memory: "256Mi"
    limit_range_default_cpu: "250m"
    limit_range_default_request_memory: "64Mi"
    limit_range_default_request_cpu: "25m"
    quota_requests_memory: "8Gi"
    quota_limits_memory: "16Gi"
    quota_requests_cpu: "4"
    quota_limits_cpu: "8"
  optional:
    limit_range_default_memory: "256Mi"
    limit_range_default_cpu: "250m"
    limit_range_default_request_memory: "64Mi"
    limit_range_default_request_cpu: "25m"
    quota_requests_memory: "8Gi"
    quota_limits_memory: "16Gi"
    quota_requests_cpu: "4"
    quota_limits_cpu: "8"
