# Copyright 2025 Alejandro Martínez Corriá and the Thinkube contributors
# SPDX-License-Identifier: Apache-2.0

---
# k8s-hostpath StorageClass
#
# This StorageClass provides compatibility with Thinkube playbooks that reference
# "k8s-hostpath" storage. It uses the Canonical k8s-snap's default OpenEBS Rawfile CSI
# provisioner as the backend.
#
# This acts as an alias to csi-rawfile-default, allowing Thinkube to maintain a
# consistent storage naming convention across different Kubernetes distributions
# while using the optimized storage backend provided by k8s-snap.
#
# Features:
#   - Dynamic volume provisioning using rawfile.csi.openebs.io
#   - WaitForFirstConsumer binding mode (volumes created when pod scheduled)
#   - Volume expansion support
#   - Delete reclaim policy (volumes deleted when PVC is deleted)
#
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: k8s-hostpath
  labels:
    app.kubernetes.io/name: k8s-hostpath
    app.kubernetes.io/part-of: thinkube
    app.kubernetes.io/component: storage
provisioner: rawfile.csi.openebs.io
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  # OpenEBS Rawfile CSI parameters
  # The provisioner creates raw disk image files on the host filesystem
  # and mounts them as loop devices for container use
  fsType: "ext4"
