# Copyright 2025 Alejandro Martínez Corriá and the Thinkube contributors
# SPDX-License-Identifier: Apache-2.0

---
# ansible/40_thinkube/core/seaweedfs/17_configure_discovery.yaml
# Description:
#   Configure service discovery for SeaweedFS by creating a ConfigMap
#   that describes the service endpoints and metadata
#
# Requirements:
#   - SeaweedFS must be deployed
#   - MicroK8s kubectl access
#
# Usage:
#   cd ~/thinkube
#   ./scripts/run_ansible.sh ansible/40_thinkube/core/seaweedfs/17_configure_discovery.yaml
#
# Variables from inventory:
#   - domain_name: Base domain for the cluster
#   - kubeconfig: Path to kubeconfig file

- name: Configure SeaweedFS service discovery
  hosts: microk8s_control_plane
  gather_facts: true
  
  tasks:
    - name: Create service discovery ConfigMap
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        state: present
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: thinkube-service-config
            namespace: seaweedfs
            labels:
              thinkube.io/managed: "true"
              thinkube.io/service-type: "core"
              thinkube.io/service-name: "seaweedfs"
          data:
            service.yaml: |
              service:
                name: seaweedfs
                display_name: "SeaweedFS"
                description: "Distributed file storage system"
                type: core
                category: storage
                icon: /icons/tk_data.svg
                
                endpoints:
                  - name: web
                    type: http
                    url: "https://seaweedfs.{{ domain_name }}"
                    health_path: "/"
                    description: "Web interface"
                    primary: true
                    
                dependencies: []
                  
                scaling:
                  resource_type: statefulset
                  resource_name: seaweedfs-master
                  namespace: seaweedfs
                  min_replicas: 1
                  can_disable: false
                  
    - name: Verify ConfigMap creation
      kubernetes.core.k8s_info:
        kubeconfig: "{{ kubeconfig }}"
        api_version: v1
        kind: ConfigMap
        name: thinkube-service-config
        namespace: seaweedfs
      register: configmap_info
      
    - name: Display ConfigMap status
      ansible.builtin.debug:
        msg: "Service discovery ConfigMap created for SeaweedFS"
      when: configmap_info.resources | length > 0
