---
# ansible/40_thinkube/optional/cvat/17_configure_discovery.yaml
# Description:
#   Configure service discovery for CVAT
#   Registers the service with metadata for thinkube-control
#
# Requirements:
#   - MicroK8s must be installed and running
#   - CVAT must be deployed
#
# Usage:
#   cd ~/thinkube
#   ./scripts/run_ansible.sh ansible/40_thinkube/optional/cvat/17_configure_discovery.yaml
#
# Variables from inventory:
#   - domain_name: Base domain for the cluster
#   - kubeconfig: Path to kubeconfig file
#
# 🤖 [AI-generated]

- name: Configure CVAT service discovery
  hosts: microk8s_control_plane
  gather_facts: true

  vars:
    cvat_namespace: cvat
    cvat_hostname: "cvat.{{ domain_name }}"

  tasks:
    - name: Verify required variables are defined
      ansible.builtin.assert:
        that:
          - domain_name is defined
          - kubeconfig is defined
        fail_msg: "Required variables are not defined"

    - name: Create service discovery ConfigMap
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        state: present
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: thinkube-service-config
            namespace: "{{ cvat_namespace }}"
            labels:
              thinkube.io/managed: "true"
              thinkube.io/service-type: "optional"
              thinkube.io/service-name: "cvat"
          data:
            service.yaml: |
              service:
                name: cvat
                display_name: "CVAT"
                description: "Computer Vision Annotation Tool for image and video labeling"
                type: optional
                category: ai
                icon: /icons/tk_ai.svg

                endpoints:
                  - name: dashboard
                    type: http
                    url: "https://{{ cvat_hostname }}"
                    health_url: "https://{{ cvat_hostname }}/api/health"
                    description: "Annotation interface"
                    primary: true
                  - name: api
                    type: http
                    url: "https://{{ cvat_hostname }}/api"
                    description: "REST API endpoint"

                dependencies:
                  - postgresql
                  - valkey

                scaling:
                  resource_type: deployment
                  resource_name: cvat-server
                  namespace: "{{ cvat_namespace }}"
                  min_replicas: 1
                  can_disable: true

                metadata:
                  authentication: jwt_oidc
                  supports_oidc: true
                  oidc_client_id: cvat
                  features:
                    - "Image annotation"
                    - "Video annotation"
                    - "Object detection"
                    - "Semantic segmentation"
                    - "AI-assisted labeling"

    - name: Verify ConfigMap creation
      kubernetes.core.k8s_info:
        kubeconfig: "{{ kubeconfig }}"
        api_version: v1
        kind: ConfigMap
        name: thinkube-service-config
        namespace: "{{ cvat_namespace }}"
      register: configmap_info

    - name: Display ConfigMap status
      ansible.builtin.debug:
        msg: "Service discovery ConfigMap created for CVAT"
      when: configmap_info.resources | length > 0