---
# ansible/40_thinkube/optional/cvat/19_rollback.yaml
# Description:
#   Rollback/uninstall playbook for CVAT
#   Removes all CVAT resources from the cluster
#
# Requirements:
#   - MicroK8s must be installed and running
#
# Usage:
#   cd ~/thinkube
#   ./scripts/run_ansible.sh ansible/40_thinkube/optional/cvat/19_rollback.yaml
#
# 🤖 [AI-generated]

- name: Rollback CVAT deployment
  hosts: microk8s_control_plane
  gather_facts: true

  vars:
    cvat_namespace: cvat
    keycloak_url: "https://auth.{{ domain_name }}"
    keycloak_realm: "thinkube"
    cvat_client_id: "cvat"

  tasks:
    - name: Verify kubeconfig is defined
      ansible.builtin.assert:
        that:
          - kubeconfig is defined
        fail_msg: "kubeconfig is not defined"

    - name: Check if CVAT namespace exists
      kubernetes.core.k8s_info:
        kubeconfig: "{{ kubeconfig }}"
        api_version: v1
        kind: Namespace
        name: "{{ cvat_namespace }}"
      register: namespace_check

    - name: Delete CVAT namespace (this will delete all resources in the namespace)
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        name: "{{ cvat_namespace }}"
        api_version: v1
        kind: Namespace
        state: absent
        wait: true
        wait_timeout: 300
      when: namespace_check.resources | length > 0

    - name: Remove CVAT from Keycloak
      when:
        - domain_name is defined
        - admin_username is defined
        - admin_password is defined
      block:
        - name: Get Keycloak admin token
          ansible.builtin.uri:
            url: "{{ keycloak_url }}/realms/master/protocol/openid-connect/token"
            method: POST
            body_format: form-urlencoded
            body:
              client_id: admin-cli
              username: "{{ admin_username }}"
              password: "{{ admin_password }}"
              grant_type: password
            validate_certs: true
          register: keycloak_token
          failed_when: false

        - name: Get CVAT client from Keycloak
          ansible.builtin.uri:
            url: "{{ keycloak_url }}/admin/realms/{{ keycloak_realm }}/clients?clientId={{ cvat_client_id }}"
            method: GET
            headers:
              Authorization: "Bearer {{ keycloak_token.json.access_token }}"
            validate_certs: true
          register: cvat_client
          when: keycloak_token is succeeded
          failed_when: false

        - name: Delete CVAT client from Keycloak
          ansible.builtin.uri:
            url: "{{ keycloak_url }}/admin/realms/{{ keycloak_realm }}/clients/{{ cvat_client.json[0].id }}"
            method: DELETE
            headers:
              Authorization: "Bearer {{ keycloak_token.json.access_token }}"
            validate_certs: true
            status_code: [204, 404]
          when:
            - keycloak_token is succeeded
            - cvat_client is succeeded
            - cvat_client.json | length > 0
          failed_when: false

    - name: Verify namespace is deleted
      kubernetes.core.k8s_info:
        kubeconfig: "{{ kubeconfig }}"
        api_version: v1
        kind: Namespace
        name: "{{ cvat_namespace }}"
      register: final_check
      failed_when: final_check.resources | length > 0

    - name: Display rollback status
      ansible.builtin.debug:
        msg:
          - "CVAT has been successfully removed from the cluster"
          - "All resources in the {{ cvat_namespace }} namespace have been deleted"
          - "Keycloak client configuration has been removed"