---
# Default values for httproute role
httproute_gateway_name: "{{ gateway_name | default('thinkube-gateway') }}"
httproute_gateway_namespace: "{{ gateway_namespace | default('gateway-system') }}"
httproute_gateway_section: "https"
httproute_path: "/"
httproute_path_type: "PathPrefix"
httproute_request_timeout: ""
httproute_backend_timeout: ""
